

services:
  delivraptor:
    build: ./src
    container_name: delivraptor
    restart: unless-stopped
    environment:
      DB_USER: sae
      DB_NAME: saedb
      DB_SERVER: postgresdb
      DB_PASSWORD: Skadjam-sae3
    volumes:
      - ./delivraptor/images:/app/images
      - ./delivraptor/logs:/app/logs
      - ./delivraptor/lst_client.data:/app/lst_client.data
    ports:
      - "6969:6969"
    networks:
      - sae
    depends_on:
     - postgres

networks:
  sae:
    external: true